version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_sentinel"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_sentinel/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_sentinel_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_sentinel_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_sentinel_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_sentinel_linux"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_sentinel_macos"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_sentinel_web"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/device_sentinel_windows"
    schedule:
      interval: "daily"