name: device_sentinel_ios
description: >-
  iOS implementation of the device_sentinel plugin for detecting hardware button
  presses and device security events using Swift.
version: 1.1.0
homepage: https://github.com/Crdzbird/device_sentinel
repository: https://github.com/Crdzbird/device_sentinel
issue_tracker: https://github.com/Crdzbird/device_sentinel/issues
topics:
  - hardware-buttons
  - device-security
  - flutter-plugin

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

flutter:
  plugin:
    implements: device_sentinel
    platforms:
      ios:
        pluginClass: DeviceSentinelPlugin
        dartPluginClass: DeviceSentinelIOS

dependencies:
  device_sentinel_platform_interface: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.2.0
